### ISSUE TITLE
Complete Stage 1

### ISSUE THREAD

**Issue by luquehuong** [hieunmce/example-go#24]
https://github.com/luquehuong/example-go/branches

**Comment by luquehuong** [comment]
#### Ready

#### Checklist

##### Stage 1:
* [x] CRUD users
* [x] CRUD categories
* [x] CRUD books
* [x] Validate category is correct before (Create/Update)
* [x] Validate books is correct before (Create/Update)
* [x] Validate user lend book

##### Stage 2:
* [X] Add testing for CRUD category:
  * [X] Validation testing
  * [X] Database testing
* [X] Add testing for CRUD books:
  * [X] Validation testing
  * [X] Database testing
* [X] Add testing for lending books:
  * [X] Validation testing
  * [X] Database testing

@hieunmce  Nhờ Hiếu review stage 1 giúp H nhé. Link branchs of project: https://github.com/luquehuong/example-go/branches
Cảm ơn Hiếu.
